version: "3"

services:
  # Proxy to service
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy_api
    depends_on:
      - backend-api
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  backend-api:
    image: backend-api
    container_name: backend-api
    build:
      context: ./
    ports:
      - 8080:80
    restart: on-failure
