version: 2.1

jobs:
  run_tests:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            cd OTOT_Task_B_Api_Server
            npm install --save
      - run:
          name: Make directory
          command: |
            cd OTOT_Task_B_Api_Server
            mkdir ~/junit
      - run:
          command: |
            cd OTOT_Task_B_Api_Server
            npx mocha test --reporter mocha-junit-reporter
          environment:
            MOCHA_FILE: ~/junit/test-results.xml
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

workflows:
  build_test:
    jobs:
      - run_tests
